server:
  servlet:
    context-path: /file-storage
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file_storage?application_name=file-storage
    username: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
poei:
  private-key: oodrive-poei
